account-service-uri: http://localhost:9090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id:
          uri: ${account-service-uri}
          predicates:
            - Path= /api/admin/** , /api/member/**
          order: 1
          filters:
            - RewritePath=/api, /
