admin-bff-uri: http://localhost:9091
member-bff-uri: http://localhost:9092

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id:
          uri: ${member-bff-uri}
          predicates:
            - Path= /api/member/**,/api/task/**
          order: 1
          filters:
            - RewritePath=/api, /

        - id:
          uri: ${admin-bff-uri}
          predicates:
            - Path= /api/admin/**
          order: 2
          filters:
            - RewritePath=/api, /



